{{- /* Commenting this out for now - needs to be created globally
{{ if (.Values.ipa.enable_kubetail) }}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-kubetail-sa
  labels:
    app.kubernetes.io/name: kubetail
    app.kubernetes.io/instance: kubetail
    app.kubernetes.io/managed-by: Helm
    release: {{ .Release.Name }}
{{ end }}
End of commented out section */}}