default_language_version:
  python: python3
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        language_version: python3
        types: [python]
        args: ["--settings-file", "pyproject.toml"]
        files: ^src/
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        require_serial: true
        args: ["--config", "pyproject.toml"]
        files: ^src/
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true
        files: ^src/
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true
        args: ["--config", ".flake8"]
        files: ^src/
