{{- if eq (default .Values.ipa.enable_ipazero false) true }}
{{- if .Values.ipazero.create_rbac }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Chart.Name }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-{{ .Chart.Name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}