{{- if eq (default .Values.ipa.enable_ipazero false) true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-redis
  labels:
    app: {{ .Chart.Name }}
    component: redis
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 6379
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-redis
    release: {{ .Release.Name }}
{{ end }}