name: optimization
description: Demonstrates a typical FICO Xpress pipeline. Uses a FICO demonstration model of a stock portfolio optimization
experiment: exp_optim
compute: small
runtime: runtime_optimization
params:
    max_risky_stocks: 3
    max_risky_stocks_ratio: 0.25
    max_ratio_per_stock: 0.3
    min_ratio_per_stock: 0.01
    min_ratio_per_region: 0.2
    min_stocks_per_region: 2
    max_total_stocks: 8
    max_number_risky_sum_activation: 'hard'
    min_number_per_region_activation: 'soft'
scope: optimization
platforms:
    - AML
    - Local
    - DBR
    - Vertex
input_output_slots:
-   name: industries_and_regions.xlsx
    type: cloudfile
    url: cloud://{config.data_dir}/industries_and_regions.xlsx
-   name: stocks.csv
    type: cloudfile
    url: cloud://{config.data_dir}/stocks.csv
-   name: dq_warnings.log
    type: cloudfile
    url:  cloud://{config.output_dir}/{utc_year}-{utc_month}-{utc_day}_{run_id}/logs/dq_warnings.log
-   name: solution_dq_warnings.log
    type: cloudfile
    url:  cloud://{config.output_dir}/{utc_year}-{utc_month}-{utc_day}_{run_id}/logs/solution_dq_warnings.log
-   name: output_dir
    type: cloudfile
    url: cloud://{config.output_dir}/{utc_year}-{utc_month}-{utc_day}_{run_id}
    is_dir: true
-   name: output.csv
    type: cloudfile
    url: cloud://{config.output_dir}/{utc_year}-{utc_month}-{utc_day}_{run_id}/csv/output.csv
-   name: output_ge_warning.html
    type: cloudfile
    url: cloud://{config.output_dir}/{utc_year}-{utc_month}-{utc_day}_{run_id}/logs/output_ge_warning.html
steps:
-   class: template_pipelines.steps.optimization.copy_input_to_ioctx:CopyInputToIoctx
    name: copy_input_to_ioctx
    inputs: 
        - industries_and_regions.xlsx
        - stocks.csv
-   class: aif.pyrogai.steps:DqStep
    name: input_dq
    run_after:
        - copy_input_to_ioctx
-   class: template_pipelines.steps.optimization.preprocess_data:PreprocessData
    name: preprocess_data
    run_after:
        - input_dq
-   class: aif.pyrogai.steps:DqStep
    name: preprocessed_dq
    run_after:
        - preprocess_data
-   class: template_pipelines.steps.optimization.preprocessed_critical_custom_dq:PreprocessedCriticalCustomDq
    name: preprocessed_critical_custom_dq
    run_after:
        - preprocess_data
-   class: template_pipelines.steps.optimization.preprocessed_warning_custom_dq:PreprocessedWarningCustomDq
    name: preprocessed_warning_custom_dq
    outputs:
        - dq_warnings.log
    run_after:
        - preprocess_data
-   class: template_pipelines.steps.optimization.formulate_and_solve:FormulateAndSolve
    name: formulate_and_solve
    run_after:
        - preprocessed_dq
        - preprocessed_critical_custom_dq
-   class: aif.pyrogai.steps:DqStep
    name: solution_dq
    run_after:
        - formulate_and_solve
-   class: template_pipelines.steps.optimization.solution_custom_dq:SolutionCustomDq
    name: solution_custom_dq
    outputs:
        - solution_dq_warnings.log
    run_after:
        - formulate_and_solve
-   class: template_pipelines.steps.optimization.postprocess_data:PostprocessData
    name: postprocess_data
    run_after:
        - formulate_and_solve
-   class: template_pipelines.steps.optimization.output_dq_with_save_to_ioslots:OutputWithSaveToIoslotsDqStep
    name: output_dq_with_save_to_ioslots
    run_after:
        - solution_dq
        - solution_custom_dq
        - postprocess_data
    outputs:
        - output_dir
        - output.csv
        - output_ge_warning.html
