name: gu_translation
description: Demonstrates a simplified Generative AI pipeline for text translation. Beta version
experiment: exp_ml
compute: small
runtime: runtime_gu_translation
scope: gu-translation
platforms:
    - Local
    - AML

params:
  text: "Savor the Flavor of Vietnam: Pho-nomenal Pho for Everyone!"
  original_language: "EN"
  target_languages: "DE,FR,VI,KO,SV"

steps:
-   name: translation
    class: template_pipelines.steps.gu_translation.translation:Translation