# In order for this action to work you need to create labels manually beforehand
name: Auto Label
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  call-deployment:
    name: Run Development
    needs: [auto-label]
    uses: ./.github/workflows/development.yaml
    secrets: inherit
