name: Update index.json
run-name: ${{ github.actor }} is running Development Deployment

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          
      - name: execute verification and update script # run file
        run: |
          find . -maxdepth 3
          python ./scripts/verify_update_index.py

      - name: add remote
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add index.json src/template_pipelines/config/pipeline_*.yml
      - name: authenticate
        run: |
          git config --global user.email ${{ secrets.mail }}
          git config --global user.name ${{ secrets.name }}
      - name: commit changed files
        run: git commit -m "update pipelines"
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main
