on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: release-please-action

      - name: Send notification to Teams
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          latest_release=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/latest)
          release_tag=$(echo "$latest_release" | jq -r .tag_name)
          release_notes=$(echo "$latest_release" | jq -r .body)

          curl -H 'Content-Type: application/json' \
               -d '{
                    "title": "New Release: '"$release_tag"'",
                    "text": "'"$release_notes"'"
                  }' \
               ${{ secrets.TEAMS_WEBHOOK_URL }}
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
